# Site settings
title: Danai Vernadaki
description: Trainee in Data Analysis
baseurl: https://danaive.github.io/profile
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Danai Vernadaki
user_description: I'm a Data Analyst enthousiast from Athens, eager to explore the world of data.
user_title: Global Trade and Market Analyst
email: danaivernadaki@gmail.com

linkedin_profile: https://www.linkedin.com/in/dvernadaki/
github_username:  DanaiVe
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

